/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 */
public class Utilizador_menu extends javax.swing.JFrame {

    
    protected String utilizador_nome;
    protected Chat_cliente cliente;
    protected int tipo_msg;
    protected String nome_grupo_antigo;
    public File ficheiro;
    
    public Utilizador_menu() {
        initComponents();

        this.cliente = null;
        this.utilizador_nome = "";
        this.nome_grupo_antigo = "";
        Bt_envia_mensagem.setEnabled(false);
        Anexar_ficheiro.setVisible(false);
        Lb_remover.setVisible(false);
        Lb_sair.setVisible(false);
        lb_sair.setVisible(false);
        lb_apagar.setVisible(false);


    }

    public void chat_menu(Chat_cliente cliente, String utilizador_nome) {

        this.utilizador_nome = utilizador_nome;
        ComponentMover cm = new ComponentMover(this, jPanel1);
        this.cliente = cliente;
        Lb_utilizador.setText(utilizador_nome);
        this.Anexar_ficheiro.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_close_window = new javax.swing.JLabel();
        jLabel_minimizar = new javax.swing.JLabel();
        Lb_utilizador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_apagar = new javax.swing.JLabel();
        lb_sair = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        L_utilizadores = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        L_grupos = new java.awt.List();
        B_novo_grupo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Mensagem = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Lb_sair = new javax.swing.JLabel();
        Lb_remover = new javax.swing.JLabel();
        Tb_mensagem = new javax.swing.JTextField();
        Bt_envia_mensagem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        L_utilizadores_grupo = new java.awt.List();
        Anexar_ficheiro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");

        jLabel_close_window.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel_close_window.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close_window.setText("x");
        jLabel_close_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_close_windowMouseClicked(evt);
            }
        });

        jLabel_minimizar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimizar.setText("-");
        jLabel_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizarMouseClicked(evt);
            }
        });

        Lb_utilizador.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Happy Chat");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Saida.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        lb_apagar.setText("Apagar Grupo");

        lb_sair.setText("Sair Grupo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_utilizador)
                .addGap(165, 165, 165)
                .addComponent(jLabel2)
                .addGap(150, 150, 150)
                .addComponent(lb_apagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_sair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_minimizar)
                .addGap(18, 18, 18)
                .addComponent(jLabel_close_window)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Lb_utilizador)
                    .addComponent(lb_apagar)
                    .addComponent(lb_sair))
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_close_window)
                        .addComponent(jLabel_minimizar))
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        L_utilizadores.setBackground(new java.awt.Color(0, 102, 102));
        L_utilizadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L_utilizadores.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        L_utilizadores.setForeground(new java.awt.Color(255, 255, 255));
        L_utilizadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_utilizadoresMouseClicked(evt);
            }
        });
        L_utilizadores.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                L_utilizadoresHierarchyChanged(evt);
            }
        });
        L_utilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_utilizadoresActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grupos");

        L_grupos.setBackground(new java.awt.Color(0, 102, 102));
        L_grupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L_grupos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        L_grupos.setForeground(new java.awt.Color(255, 255, 255));
        L_grupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_gruposMouseClicked(evt);
            }
        });

        B_novo_grupo.setBackground(new java.awt.Color(51, 102, 255));
        B_novo_grupo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_novo_grupo.setForeground(new java.awt.Color(255, 255, 255));
        B_novo_grupo.setText("+");
        B_novo_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_novo_grupoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Utilizadores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(L_utilizadores, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(L_grupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(B_novo_grupo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(L_utilizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L_grupos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(B_novo_grupo)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        TA_Mensagem.setEditable(false);
        TA_Mensagem.setColumns(20);
        TA_Mensagem.setRows(5);
        jScrollPane1.setViewportView(TA_Mensagem);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));

        jLabel5.setText("Chat");

        Lb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        Lb_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lb_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lb_sairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_sairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_sairMouseExited(evt);
            }
        });

        Lb_remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.png"))); // NOI18N
        Lb_remover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lb_remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lb_removerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_removerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_removerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lb_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lb_sair)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb_remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        Tb_mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tb_mensagemActionPerformed(evt);
            }
        });
        Tb_mensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tb_mensagemKeyPressed(evt);
            }
        });

        Bt_envia_mensagem.setText("Send");
        Bt_envia_mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_envia_mensagemActionPerformed(evt);
            }
        });
        Bt_envia_mensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Bt_envia_mensagemKeyPressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Grupo");

        L_utilizadores_grupo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L_utilizadores_grupo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        L_utilizadores_grupo.setForeground(new java.awt.Color(255, 0, 102));
        L_utilizadores_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_utilizadores_grupoMouseClicked(evt);
            }
        });
        L_utilizadores_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_utilizadores_grupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_utilizadores_grupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(L_utilizadores_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Anexar_ficheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/anexo_1.png"))); // NOI18N
        Anexar_ficheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Anexar_ficheiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Tb_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Anexar_ficheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Bt_envia_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tb_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Anexar_ficheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bt_envia_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L_utilizadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_utilizadoresMouseClicked
        List list = (List) evt.getSource();
        if (evt.getClickCount() == 2) {
            try {
                tipo_msg = Mensagem.MENSAGEM_CHAT_PRIVATE;
                Lb_remover.setVisible(false);
                Lb_sair.setVisible(false);

                L_grupos.deselect(L_grupos.getSelectedIndex());
//                JOptionPane.showMessageDialog(this, "Utilizador " + L_utilizadores.getItem(L_utilizadores.getSelectedIndex()));
                Bt_envia_mensagem.setEnabled(true);
                Anexar_ficheiro.setVisible(true);

                TA_Mensagem.setText("");

//                ArrayList<Mensagens> aaa = new File_Management().Le_Objeto_Ficheiro("mensagens.txt");
//
//                Iterator<Mensagens> itr = client.getClient().getMensagens().iterator();
//
//                while (itr.hasNext()) {
//                    Mensagens ut = itr.next();
//                    //(ut.getUser_recebeu().equals(utilizador_nome) && L_utilizadores.getItem(L_utilizadores.getSelectedIndex()).equals(ut.getUser_enviou())) || (ut.getUser_enviou().equals(utilizador_nome) && ut.getUser_recebeu().equals(L_utilizadores.getItem(L_utilizadores.getSelectedIndex())))
//                    if (ut.getUser_recebeu().equals(utilizador_nome) && ut.getUser_enviou().equals(L_utilizadores.getSelectedItem())) {
//                        //TA_mensagens.append(ut.getConteudo_msm());
//
//                        TA_Mensagem.append("  Me " + ut.getConteudo_msm());
//
//                    } else if (ut.getUser_enviou().equals(utilizador_nome) && ut.getUser_recebeu().equals(L_utilizadores.getSelectedItem())) {
//                        //TA_mensagens.append(ut.getConteudo_msm());
//                        TA_Mensagem.append( "  "+ut.getConteudo_msm());
//
//                    }
//                }
            } catch (ArrayIndexOutOfBoundsException e) {
                System.err.println(e);
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_L_utilizadoresMouseClicked

    private void B_novo_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_novo_grupoActionPerformed

        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();

        String nome_novo_grupo = JOptionPane.showInputDialog(this, "Nome do novo grupo");

        if (nome_novo_grupo != null) {
            if (!nome_novo_grupo.trim().isEmpty()) {

                try {
                    cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.GRUPO,cliente.getId_cliente(), utilizador_nome, "Server", nome_novo_grupo, "" + dateFormat.format(date)));

                } catch (RemoteException ex) {
                    Logger.getLogger(Utilizador_menu.class.getName()).log(Level.SEVERE, "CRIAR GRUPO", ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nome do grupo vazio");
            }
        }


    }//GEN-LAST:event_B_novo_grupoActionPerformed

    private void L_gruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_gruposMouseClicked
        List list = (List) evt.getSource();

        if (evt.getClickCount() == 2) {
            if (L_grupos.getSelectedItem() != null) {
                tipo_msg = Mensagem.GRUPO_MSM;
                Lb_remover.setVisible(true);
                Lb_sair.setVisible(true);

                L_utilizadores.deselect(L_utilizadores.getSelectedIndex());
//                JOptionPane.showMessageDialog(this, "Utilizador " + L_utilizadores.getItem(L_utilizadores.getSelectedIndex()));
                Bt_envia_mensagem.setEnabled(true);
                Anexar_ficheiro.setVisible(true);

                TA_Mensagem.setText("");

//                if (client.getClient().getInicia() != null) {
//                    nome_grupo_antigo = client.getClient().getInicia().getNome_grupo();
                    if (L_grupos.getSelectedItem().equals(nome_grupo_antigo)) {
                        nome_grupo_antigo = "-1";
                    }
//                }

                try {
//                    cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.GRUPO,cliente.getId_cliente(), utilizador_nome, "Server", nome_novo_grupo, "" + dateFormat.format(date)));

                cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.GRUPO_JUNTAR, cliente.getId_cliente(),utilizador_nome, L_grupos.getSelectedItem(), nome_grupo_antigo, "ALTERAR GRUPO"));
                } catch (RemoteException ex) {
                    Logger.getLogger(Utilizador_menu.class.getName()).log(Level.SEVERE, "mudar grupo", ex);
                }

            }
        }
    }//GEN-LAST:event_L_gruposMouseClicked

    private void L_utilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_utilizadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_utilizadoresActionPerformed

    private void jLabel_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizarMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizarMouseClicked

    private void jLabel_close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close_windowMouseClicked
       
        boolean chat_que_esta_usar = true;
        try {
            if (tipo_msg == Mensagem.MENSAGEM_CHAT_PRIVATE) {
                chat_que_esta_usar = true;
            } else if (tipo_msg == Mensagem.GRUPO_MSM) {
                chat_que_esta_usar = false;
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            System.err.println("Erro ao selecionar " + e);
        }
        try {
                
            cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.SAIR,cliente.getId_cliente(),chat_que_esta_usar ));
            cliente.menu_utilizador.dispose();
            cliente.menu_inicial.dispose();
        } catch (RemoteException ex) {
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel_close_windowMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Tem a certeza que pretende sair?", "Warning", dialogButton);

        if (dialogResult == JOptionPane.YES_OPTION) {
            boolean chat_que_esta_usar = true;
            try {
                if (tipo_msg == Mensagem.MENSAGEM_CHAT_PRIVATE) {
                    chat_que_esta_usar = true;
                } else if (tipo_msg == Mensagem.GRUPO_MSM) {
                    chat_que_esta_usar = false;
                }

            } catch (ArrayIndexOutOfBoundsException e) {
                System.err.println("Erro ao selecionar " + e);
            }
            try {

                cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.SAIR, cliente.getId_cliente(), chat_que_esta_usar));
                cliente.menu_utilizador.dispose();
                cliente.menu_inicial.dispose();
            } catch (RemoteException ex) {
                System.out.println("error back");
            }
            new Chat_cliente();
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void Tb_mensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tb_mensagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tb_mensagemActionPerformed

    private void L_utilizadores_grupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_utilizadores_grupoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_L_utilizadores_grupoMouseClicked

    private void L_utilizadores_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_utilizadores_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_utilizadores_grupoActionPerformed

    private void Bt_envia_mensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_envia_mensagemActionPerformed
        String msg = Tb_mensagem.getText();
        String target_nome = "";
//
        try {
            if (tipo_msg == Mensagem.MENSAGEM_CHAT_PRIVATE) {
                target_nome = L_utilizadores.getSelectedItem();
            } else if (tipo_msg == Mensagem.GRUPO_MSM) {
                target_nome = L_grupos.getSelectedItem();
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            System.err.println("Erro ao selecionar " + e);
        }
        
        if (ficheiro != null) {
            long size = ficheiro.length();
            if (size < 120 * 1024 * 1024) {
                try {
                    cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.PED_ENVIAR_FICHEIRO,cliente.getId_cliente(), utilizador_nome, target_nome, ficheiro.getName(), "Envio Ficheiro"));
                } catch (RemoteException ex) {
                    Logger.getLogger(Utilizador_menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {

                TA_Mensagem.append("[Application > Me] : O ficheiro é demasiado grande!");

            }
        }

        if (!msg.trim().isEmpty() && !target_nome.trim().isEmpty()) {
            try {
                Tb_mensagem.setText("");
                //                                          (int REGISTO, int id_cliente, String nome_quem enviou, String quem_recebe, String msm, String aux)
                cliente.getS_comunica().comunica_com_server(new Mensagem(tipo_msg, cliente.getId_cliente(), utilizador_nome, target_nome, msg, "Mensagem"));
            } catch (RemoteException ex) {
                Logger.getLogger(Utilizador_menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_Bt_envia_mensagemActionPerformed

    private void L_utilizadoresHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_L_utilizadoresHierarchyChanged

    }//GEN-LAST:event_L_utilizadoresHierarchyChanged

    private void Anexar_ficheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anexar_ficheiroMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showDialog(this, "Select File");
        ficheiro = fileChooser.getSelectedFile();

        if (ficheiro != null) {
            if (!ficheiro.getName().isEmpty()) {
                String str;
                String path = ficheiro.getPath();

                if (path.length() > 30) {
                    String t = path;
                    str = t.substring(0, 20) + " [...] " + t.substring(t.length() - 20, t.length());
                } else {
                    str = path;
                }

                TA_Mensagem.append("[Application] : Ficheiro carregado!");

            } else {

                TA_Mensagem.append("[Application] : Erro ao carregar ficheiro!");

            }
        }
    }//GEN-LAST:event_Anexar_ficheiroMouseClicked

    private void Tb_mensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tb_mensagemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ActionEvent actionevent = null;
            this.Bt_envia_mensagemActionPerformed(actionevent);
        }
    }//GEN-LAST:event_Tb_mensagemKeyPressed

    private void Bt_envia_mensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bt_envia_mensagemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ActionEvent actionevent = null;
            this.Bt_envia_mensagemActionPerformed(actionevent);
        }
    }//GEN-LAST:event_Bt_envia_mensagemKeyPressed

    private void Lb_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_sairMouseClicked

        String target_nome_grupo = "";
        try {
            target_nome_grupo = L_grupos.getSelectedItem();
        } catch (ArrayIndexOutOfBoundsException ex) {
            System.out.println(ex);
            target_nome_grupo = "";
        }

        if (!target_nome_grupo.trim().isEmpty()) {
            
                Tb_mensagem.setText("");
            try {
                cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.SAIR_GRUPO, cliente.getId_cliente(), target_nome_grupo, "Remover", "Sair Grupo"));
            } catch (RemoteException ex) {
                Logger.getLogger(Utilizador_menu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_Lb_sairMouseClicked

    private void Lb_removerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_removerMouseClicked
        String target_nome_grupo = "";
        try {
            target_nome_grupo = L_grupos.getSelectedItem();
        } catch (ArrayIndexOutOfBoundsException ex) {
            System.out.println(ex);
            target_nome_grupo = "";
        }
//        
//        String nome_grupo_antigo = "";
        if (!target_nome_grupo.trim().isEmpty() ) {
            Tb_mensagem.setText("");
            try {
                cliente.getS_comunica().comunica_com_server(new Mensagem(Mensagem.REMOVER_GRUPO, cliente.getId_cliente(), target_nome_grupo, "Remover", "Sair Grupo"));
            } catch (RemoteException ex) {
                Logger.getLogger(Utilizador_menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Lb_removerMouseClicked

    private void Lb_removerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_removerMouseEntered
        lb_apagar.setVisible(true);
    }//GEN-LAST:event_Lb_removerMouseEntered

    private void Lb_removerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_removerMouseExited
        lb_apagar.setVisible(false);
    }//GEN-LAST:event_Lb_removerMouseExited

    private void Lb_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_sairMouseEntered
        lb_sair.setVisible(true);
    }//GEN-LAST:event_Lb_sairMouseEntered

    private void Lb_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_sairMouseExited
        lb_sair.setVisible(false);
    }//GEN-LAST:event_Lb_sairMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anexar_ficheiro;
    private javax.swing.JButton B_novo_grupo;
    public javax.swing.JButton Bt_envia_mensagem;
    public java.awt.List L_grupos;
    public java.awt.List L_utilizadores;
    public java.awt.List L_utilizadores_grupo;
    public javax.swing.JLabel Lb_remover;
    public javax.swing.JLabel Lb_sair;
    private javax.swing.JLabel Lb_utilizador;
    public javax.swing.JTextArea TA_Mensagem;
    private javax.swing.JTextField Tb_mensagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_close_window;
    private javax.swing.JLabel jLabel_minimizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_apagar;
    private javax.swing.JLabel lb_sair;
    // End of variables declaration//GEN-END:variables

    

    public String getUtilizador_nome() {
        return utilizador_nome;
    }

    public void setUtilizador_nome(String utilizador_nome) {
        this.utilizador_nome = utilizador_nome;
    }

}
